apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: demochart
spec: 
  selector: 
    matchLabels: 
      app: myapp
  strategy:
    type: {{ .Values.strategyType }}
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
  replicas: 1 
  template: 
    metadata: 
      labels: 
        app: myapp 
    spec: 
      containers: 
      - name: mycicdcontainer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.service.targetport }}
        readinessProbe:
          periodSeconds: 25
          initialDelaySeconds: 10
          tcpSocket:
            port: {{ .Values.service.targetport }} 
        livenessProbe:
          periodSeconds: 25
          initialDelaySeconds: 10
          tcpSocket:
            port: {{ .Values.service.targetport }}
        resources:
           requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
           limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
