apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: demochart
spec: 
  selector: 
    matchLabels: 
      app: myapp 
  replicas: 1 
  template: 
    metadata: 
      labels: 
        app: myapp 
    spec: 
      containers: 
      - name: mycicdcontainer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.service.targetport }}
        readinessProbe:
          periodSeconds: 25
          initialDelaySeconds: 10
          tcpSocket:
            port: {{ .Values.service.targetport }} 
        livenessProbe:
          periodSeconds: 25
          initialDelaySeconds: 10
          tcpSocket:
            port: {{ .Values.service.targetport }}
        volumeMounts:
        - name: aws-credentials
          mountPath: /root/.aws
      volumes:
      - name: aws-credentials
        secret:
          secretName: aws-credentials

