apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: demochart
spec: 
  selector: 
    matchLabels: 
      app: myapp 
  replicas: 1 
  template: 
    metadata: 
      labels: 
        app: myapp 
    spec: 
      containers: 
      - name: mycicdcontainer
        image: 281600030161.dkr.ecr.us-east-1.amazonaws.com/argocd-test:f6cec58a33a1e3edb1127710d5fa3cda3a2cd164
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.service.targetport }}
        readinessProbe:
          periodSeconds: 25
          initialDelaySeconds: 10
          tcpSocket:
            port: {{ .Values.service.targetport }} 
        livenessProbe:
          periodSeconds: 25
          initialDelaySeconds: 10
          tcpSocket:
            port: {{ .Values.service.targetport }}
        volumeMounts:
        - name: aws-credentials
          mountPath: /root/.aws
      volumes:
      - name: aws-credentials
        secret:
          secretName: aws-credentials

