apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - backend:
          service:
            name: myservice3
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
      - backend:
          service:
            name: myservice3
            port:
              number: {{ .Values.service.port }}
        path: /tea
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: {{ .Values.secretname }}
