apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mynewargoapp
  namespace: argocd
spec:
  project: default      

  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Iam-jayabharathi/argocd.git
    path: demochart
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
    - CreateNamespace:true

    automated:
      selfHeal: true
      prune: true
