namespace: default  

replicas: 1
version: v1

image:
  repository: 281600030161.dkr.ecr.us-east-1.amazonaws.com/argocd-test
  pullPolicy: IfNotPresent
  tag: 3082004bfb7f41624cdae3954b84c85037c9e133


app: node
tea: node

strategyType: RollingUpdate
maxSurge: 1
maxUnavailable: 0

service:
  port: 80
  targetport: 3000

restartPolicy: Always
secretname: aximdemosecret-tls
hostname: noc.aximsoft.com
