namespace: default  

replicas: 1
version: v1

image:
  repository: 281600030161.dkr.ecr.us-east-1.amazonaws.com/argocd-test
  pullPolicy: IfNotPresent
  tag: df15b9da5c075986e264cbd40148af8b9aeffa8c

strategyType: RollingUpdate
maxSurge: 1
maxUnavailable: 0

service:
  port: 80
  targetport: 3000

resources:
  requests:
    memory: 40Mi
    cpu: 30m
  limits:
    memory: 80Mi
    cpu: 70m

restartPolicy: Always
secretname: aximdemosecret-tls
hostname: noc.aximsoft.com
