namespace: default  

replicas: 1
version: v1

image:
  repository: 281600030161.dkr.ecr.us-east-1.amazonaws.com/argocd-test
  pullPolicy: IfNotPresent
  tag: 34afdf233275722ca52137c2cd9c04b96a5f171b

strategyType: RollingUpdate
maxSurge: 1
maxUnavailable: 0

service:
  port: 80
  targetport: 3000

resources:
  requests:
    memory: 40Mi
    cpu: 30m
  limits:
    memory: 80Mi
    cpu: 70m

restartPolicy: Always
secretname: aximdemosecret-tls
hostname: noc.aximsoft.com
